name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #checks out the repo under $GITHUB_WORKSPACE, so our job can access it

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run tests
        run: python -m unittest discover -s tests